// ============================================================
// seed.js — Dummy Data Seeder
// ============================================================

const Seeder = (() => {
  const SEEDED_KEY = "ruet_seeded_v12";

  async function run() {
    if (DB.has(SEEDED_KEY)) return;
    await _seedUsers();
    _seedProducts();
    _seedOrders();
    _seedReviews();
    DB.set(SEEDED_KEY, true);
    console.info("[Seeder] v12 data loaded.");
  }

  async function reset() {
    DB.remove(SEEDED_KEY);
    DB.remove("ruet_users");
    DB.remove("ruet_products");
    DB.remove("ruet_orders");
    DB.remove("ruet_reviews");
    DB.remove("ruet_session");
    DB.remove("ruet_login_attempts");
    DB.remove("ruet_theme");
    for (let i = localStorage.length - 1; i >= 0; i--) {
      const key = localStorage.key(i);
      if (key && (key.startsWith('ruet_cart_') || key.startsWith('ruet_wishlist_'))) {
        localStorage.removeItem(key);
      }
    }
    await run();
  }

  // ── Users ────────────────────────────────────────────────
  async function _seedUsers() {
    async function hp(password) {
      if (window.crypto && window.crypto.subtle) {
        try {
          const encoder = new TextEncoder();
          const keyMaterial = await window.crypto.subtle.importKey(
            "raw",
            encoder.encode(password),
            { name: "PBKDF2" },
            false,
            ["deriveBits", "deriveKey"]
          );
          const salt = encoder.encode("ruet_salt_v3_secure");
          const hashBuffer = await window.crypto.subtle.deriveBits(
            {
              name: "PBKDF2",
              salt: salt,
              iterations: 100000,
              hash: "SHA-256"
            },
            keyMaterial,
            256
          );
          const hashArray = Array.from(new Uint8Array(hashBuffer));
          return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
        } catch(e) {}
      }
      return btoa(btoa(password + "_ruet_salt") + "_v2");
    }

    const users = [
      // Admins
      {
        id: "admin_001",
        name: "Ashraful Anower Shakib",
        email: "ashrafulanower@ruetshop.com",
        rawPassword: "admin01@shakib",
        role: "admin",
        phone: "01816-442249",
        address: "Dept. of ECE, RUET Campus, Rajshahi-6204",
        avatar: "assets/admin_images/admin01_ashraful_anower.jpg",
        bio: "Founder, CEO & Lead Developer",
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 90,
      },
      {
        id: "admin_002",
        name: "Al Saniat Samim",
        email: "saniatsamim@ruetshop.com",
        rawPassword: "admin02@samim",
        role: "admin",
        phone: "01745-233662",
        address: "Dept. of ECE, RUET Campus, Rajshahi-6204",
        avatar: "assets/admin_images/admin02_saniat_samim.jpg",
        bio: "Co-Founder, CTO & Co-Developer",
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 85,
      },
      {
        id: "admin_003",
        name: "Mohammed Sakib",
        email: "mohammedsakib@ruetshop.com",
        rawPassword: "admin03@sakib",
        role: "admin",
        phone: "01310-097126",
        address: "Dept. of ECE, RUET Campus, Rajshahi-6204",
        avatar: "assets/admin_images/admin03_mohammed_sakib.jpg",
        bio: "Co-Founder, COO & Co-Developer",
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 80,
      },
      // Vendors
      {
        id: "vendor_001",
        name: "TechZone RUET",
        email: "techzoneruet@gmail.com",
        rawPassword: "vendor123456",
        role: "vendor",
        phone: "01811-222001",
        address: "Shop A-4, RUET Market, Rajshahi",
        avatar: "",
        bio: "Electronics & Gadgets",
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 60,
      },
      {
        id: "vendor_002",
        name: "Campus Cafe",
        email: "ruetcampuscafe@gmail.com",
        rawPassword: "vendor123456",
        role: "vendor",
        phone: "01811-222002",
        address: "Shop B-7, RUET Market, Rajshahi",
        avatar: "",
        bio: "Books, Stationery & Lab Supplies",
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 55,
      },
      {
        id: "vendor_003",
        name: "Nayeem Fashion",
        email: "nayeemfashionruet@gmail.com",
        rawPassword: "vendor123456",
        role: "vendor",
        phone: "01811-222003",
        address: "Shop C-2, RUET Market, Rajshahi",
        avatar: "",
        bio: "Clothing & Accessories",
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 50,
      },
      {
        id: "vendor_004",
        name: "Campus Canteen Supplies",
        email: "ruetcampuscanteen@gmail.com",
        rawPassword: "vendor123456",
        role: "vendor",
        phone: "01811-222004",
        address: "Canteen Building, RUET Campus",
        avatar: "",
        bio: "Food & Beverages",
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 45,
      },
      {
        id: "vendor_005",
        name: "Campus Stationery",
        email: "ruetcampusstationery@gmail.com",
        rawPassword: "vendor123456",
        role: "vendor",
        phone: "01811-222005",
        address: "Shop D-2, RUET Market, Rajshahi",
        avatar: "",
        bio: "Books, Stationery & Lab Supplies",
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 55,
      },
      {
        id: "vendor_006",
        name: "RUET Fashion Hub",
        email: "ruetfashionhub@gmail.com",
        rawPassword: "vendor123456",
        role: "vendor",
        phone: "01811-222006",
        address: "Shop E-1, RUET Market, Rajshahi",
        avatar: "",
        bio: "Clothing & Accessories",
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 50,
      },
      // Regular users
      {
        id: "user_001",
        name: "Sakib Al Hasan",
        email: "sakib@student.ruet.ac.bd",
        rawPassword: "user123456",
        role: "user",
        phone: "01711-333001",
        address: "Hall-1 Room 212, RUET, Rajshahi",
        studentId: "2003021",
        avatar: "",
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
      },
      {
        id: "user_002",
        name: "Sumaiya Begum",
        email: "sumaiya@student.ruet.ac.bd",
        rawPassword: "user123456",
        role: "user",
        phone: "01911-333002",
        address: "Girls Hall Room 105, RUET, Rajshahi",
        studentId: "2104052",
        avatar: "",
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 25,
      },
      {
        id: "user_003",
        name: "Kamal Uddin",
        email: "kamal@student.ruet.ac.bd",
        rawPassword: "user123456",
        role: "user",
        phone: "01611-333003",
        address: "Hall-3 Room 318, RUET, Rajshahi",
        studentId: "1902033",
        avatar: "",
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 20,
      },
      {
        id: "user_004",
        name: "Karim Uddin",
        email: "karim@student.ruet.ac.bd",
        rawPassword: "user123456",
        role: "user",
        phone: "01711-489403",
        address: "Hall-2 Room 245, RUET, Rajshahi",
        studentId: "2101055",
        avatar: "",
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
      },
      {
        id: "user_005",
        name: "Rahim Hossain",
        email: "rahim@student.ruet.ac.bd",
        rawPassword: "user123456",
        role: "user",
        phone: "01711-3789001",
        address: "Hall-1 Room 315, RUET, Rajshahi",
        studentId: "2203021",
        avatar: "",
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 15,
      },
      {
        id: "user_006",
        name: "Alamin Hossain",
        email: "alamin@student.ruet.ac.bd",
        rawPassword: "user123456",
        role: "user",
        phone: "01711-3789591",
        address: "Hall-2 Room 115, RUET, Rajshahi",
        studentId: "2201051",
        avatar: "",
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
      },
    ];

    for (let u of users) {
      if (u.rawPassword) {
        u.password = await hp(u.rawPassword);
        delete u.rawPassword;
      }
    }
    DB.setCollection("ruet_users", users);
  }

  // ── Products ─────────────────────────────────────────────
  function _seedProducts() {
    const products = [
      // ── ELECTRONICS (20 products) ──
      {
        id: "prod_e01", vendorId: "user_001", vendorName: "Rahim Hossain",
        name: "Sony WH-1000XM5 Headphones", emoji: "🎧",
        description: "Used for 1 year, fully fresh. Industry-leading noise cancelling with Auto NC Optimizer. Up to 30 hours battery life.",
        price: 11000, originalPrice: 22000, category: "Electronics", stock: 1, condition: "Used",
        images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400&q=80"],
        tags: ["headphones", "sony", "noise cancelling", "wireless"],
        rating: 0, reviewCount: 0, sold: 0, createdAt: Date.now() - 86400000 * 20,
      },
      {
        id: "prod_e02", vendorId: "user_002", vendorName: "Sumaiya Begum",
        name: "Samsung Galaxy Buds2 Pro", emoji: "🎵",
        description: "Used for 8 months, fully functional. Intelligent ANC, 360° Audio, Hi-Fi 24-bit audio. IPX7 water resistance.",
        price: 6000, originalPrice: 12000, category: "Electronics", stock: 1, condition: "Used",
        images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&q=80"],
        tags: ["earbuds", "samsung", "anc", "wireless"],
        rating: 0, reviewCount: 0, sold: 0, createdAt: Date.now() - 86400000 * 18,
      },
      {
        id: "prod_e03", vendorId: "user_003", vendorName: "Kamal Uddin",
        name: "Logitech MX Master 3S Mouse", emoji: "🖱️",
        description: "Used for 6 months, minor scuffs on the bottom. 8K DPI any-surface tracking, MagSpeed electromagnetic scrolling.",
        price: 4500, originalPrice: 8500, category: "Electronics", stock: 1, condition: "Used",
        images: ["https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&q=80"],
        tags: ["mouse", "logitech", "wireless", "ergonomic"],
        rating: 0, reviewCount: 0, sold: 0, createdAt: Date.now() - 86400000 * 15,
      },
      {
        id: "prod_e04", vendorId: "user_001", vendorName: "Rahim Hossain",
        name: "Keychron K2 Mechanical Keyboard", emoji: "⌨️",
        description: "Used for 1 year, all keys perfectly working. Compact 75% layout, hot-swappable, Bluetooth 5.1 + USB-C, RGB backlight.",
        price: 3500, originalPrice: 7000, category: "Electronics", stock: 1, condition: "Used",
        images: ["https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=400&q=80"],
        tags: ["keyboard", "mechanical", "keychron", "rgb", "wireless"],
        rating: 0, reviewCount: 0, sold: 0, createdAt: Date.now() - 86400000 * 14,
      },
      {
        id: "prod_e05", vendorId: "vendor_001", vendorName: "TechZone RUET",
        name: "Anker 10,000mAh Power Bank", emoji: "🔋",
        description: "10000mAh compact power bank with PowerIQ 3.0 and VoltageBoost. 2 USB-A + 1 USB-C ports, charges your phone 2-3 times.",
        price: 2200, originalPrice: 2800, category: "Electronics", stock: 30, condition: "Used",
        images: ["https://images.unsplash.com/photo-1609592806596-b452c08adcb5?w=400&q=80"],
        tags: ["powerbank", "anker", "charging", "portable"],
        rating: 4.5, reviewCount: 56, sold: 123, createdAt: Date.now() - 86400000 * 12,
      },
      {
        id: "prod_e06", vendorId: "user_002", vendorName: "Sumaiya Begum",
        name: "USB-C 7-in-1 Hub Adapter", emoji: "🔌",
        description: "Brand new in box, never used. Bought it but my laptop doesn't support PD charging. 4K HDMI, 3× USB 3.0, SD/TF card reader.",
        price: 2500, originalPrice: 3200, category: "Electronics", stock: 1, condition: "New",
        images: ["https://images.unsplash.com/photo-1625895197185-efcec01cffe0?w=400&q=80"],
        tags: ["usb hub", "adapter", "hdmi", "laptop accessories"],
        rating: 0, reviewCount: 0, sold: 0, createdAt: Date.now() - 86400000 * 11,
      },
      {
        id: "prod_e07", vendorId: "vendor_001", vendorName: "TechZone RUET",
        name: "Xiaomi 33W Fast Charger", emoji: "⚡",
        description: "33W turbo charging adapter with USB-C cable included. Charges from 0–100% in under 70 minutes. Compact and travel-friendly.",
        price: 850, originalPrice: 1100, category: "Electronics", stock: 50, condition: "Used",
        images: ["https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400&q=80"],
        tags: ["charger", "fast charging", "xiaomi", "usb-c"],
        rating: 4.3, reviewCount: 87, sold: 210, createdAt: Date.now() - 86400000 * 10,
      },
      {
        id: "prod_e08", vendorId: "user_002", vendorName: "Sumaiya Begum",
        name: "TP-Link TL-WR841N WiFi Router", emoji: "📶",
        description: "Used for 2 years, upgrading so selling this. 300Mbps wireless speed, 2 external antennas. Ideal for hostel rooms.",
        price: 800, originalPrice: 2000, category: "Electronics", stock: 1, condition: "Used",
        images: ["https://images.unsplash.com/photo-1562408590-e32931084e23?w=400&q=80"],
        tags: ["router", "wifi", "tp-link", "networking"],
        rating: 0, reviewCount: 0, sold: 0, createdAt: Date.now() - 86400000 * 9,
      },
      {
        id: "prod_e09", vendorId: "vendor_001", vendorName: "TechZone RUET",
        name: "Arduino Uno R3 Starter Kit", emoji: "🤖",
        description: "Complete starter kit: Arduino Uno R3, breadboard, 65-piece jumper wires, LEDs, resistors, sensors, LCD. Perfect for EEE/CSE projects.",
        price: 1800, originalPrice: 2200, category: "Electronics", stock: 25, condition: "Used",
        images: ["https://images.unsplash.com/photo-1608564697071-ddf911d81370?w=400&q=80"],
        tags: ["arduino", "microcontroller", "iot", "robotics", "project"],
        rating: 4.8, reviewCount: 64, sold: 155, createdAt: Date.now() - 86400000 * 8,
      },
      {
        id: "prod_e10", vendorId: "vendor_001", vendorName: "TechZone RUET",
        name: "Raspberry Pi 4 Model B (4GB)", emoji: "💻",
        description: "Quad-core ARM Cortex-A72, 4GB RAM, dual HDMI 4K, USB 3.0, Gigabit Ethernet, WiFi & Bluetooth. Ideal for AI/ML projects.",
        price: 6500, originalPrice: 7800, category: "Electronics", stock: 10, condition: "Used",
        images: ["https://images.unsplash.com/photo-1587831990711-23ca6441447b?w=400&q=80"],
        tags: ["raspberry pi", "sbc", "linux", "iot", "programming"],
        rating: 4.9, reviewCount: 27, sold: 38, createdAt: Date.now() - 86400000 * 7,
      },
      {
        id: "prod_e11", vendorId: "vendor_001", vendorName: "TechZone RUET",
        name: "Digital Multimeter (Auto-Range)", emoji: "🔬",
        description: "True RMS digital multimeter with auto-range. Measures AC/DC voltage, current, resistance, capacitance, frequency, diode, and transistor.",
        price: 1200, originalPrice: 1500, category: "Electronics", stock: 22, condition: "Used",
        images: ["https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=80"],
        tags: ["multimeter", "dmm", "lab", "eee", "measurement"],
        rating: 4.6, reviewCount: 39, sold: 95, createdAt: Date.now() - 86400000 * 6,
      },
      {
        id: "prod_e12", vendorId: "vendor_001", vendorName: "TechZone RUET",
        name: "Portable LED Desk Lamp", emoji: "💡",
        description: "USB rechargeable LED lamp with 3 color modes and 5 brightness levels. Touch control, foldable arm, 800 lumen output. Perfect for study.",
        price: 980, originalPrice: 1200, category: "Electronics", stock: 35, condition: "Used",
        images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&q=80"],
        tags: ["lamp", "led", "desk", "study", "usb"],
        rating: 4.4, reviewCount: 52, sold: 130, createdAt: Date.now() - 86400000 * 5,
      },
      {
        id: "prod_e13", vendorId: "vendor_001", vendorName: "TechZone RUET",
        name: "JBL Clip 4 Bluetooth Speaker", emoji: "🔊",
        description: "Portable waterproof speaker with integrated carabiner clip. IP67 rated, 10hr playtime, JBL Pro Sound. Works outdoors and in showers.",
        price: 3500, originalPrice: 4200, category: "Electronics", stock: 14, condition: "Used",
        images: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&q=80"],
        tags: ["speaker", "jbl", "bluetooth", "waterproof", "portable"],
        rating: 4.7, reviewCount: 41, sold: 68, createdAt: Date.now() - 86400000 * 4,
      },
      {
        id: "prod_e14", vendorId: "vendor_001", vendorName: "TechZone RUET",
        name: "Laptop Stand Ergonomic (Aluminium)", emoji: "🖥️",
        description: "Adjustable aluminium laptop stand, compatible with 10–16\" laptops. 6 height settings, foldable design, anti-slip, improves posture.",
        price: 1500, originalPrice: 1800, category: "Electronics", stock: 28, condition: "New",
        images: ["https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400&q=80"],
        tags: ["laptop stand", "ergonomic", "aluminium", "posture"],
        rating: 4.5, reviewCount: 33, sold: 79, createdAt: Date.now() - 86400000 * 3,
      },
      {
        id: "prod_e15", vendorId: "vendor_001", vendorName: "TechZone RUET",
        name: "ESP32 Development Board", emoji: "🔧",
        description: "Dual-core 240MHz, built-in WiFi & Bluetooth, 4MB flash. 38 GPIO pins, ADC, DAC, I2C, SPI, UART. Great for IoT projects.",
        price: 450, originalPrice: 600, category: "Electronics", stock: 60, condition: "Used",
        images: ["https://images.unsplash.com/photo-1555664424-778a1e5e1b48?w=400&q=80"],
        tags: ["esp32", "wifi", "bluetooth", "iot", "microcontroller"],
        rating: 4.8, reviewCount: 92, sold: 284, createdAt: Date.now() - 86400000 * 2,
      },
      {
        id: "prod_e16", vendorId: "vendor_001", vendorName: "TechZone RUET",
        name: "USB 3.0 Flash Drive 64GB", emoji: "💾",
        description: "64GB USB 3.0 flash drive with read speed up to 200MB/s. Metal casing, retractable design, compatible with Windows, Mac, Linux.",
        price: 680, originalPrice: 850, category: "Electronics", stock: 80, condition: "Used",
        images: ["https://images.unsplash.com/photo-1618410320928-25228d811631?w=400&q=80"],
        tags: ["flash drive", "usb", "storage", "64gb"],
        rating: 4.3, reviewCount: 118, sold: 345, createdAt: Date.now() - 86400000 * 1,
      },
      {
        id: "prod_e17", vendorId: "vendor_001", vendorName: "TechZone RUET",
        name: "Webcam 1080p HD with Mic", emoji: "📹",
        description: "Full HD 1080p webcam with built-in stereo microphone, autofocus, 90° wide angle. Plug-and-play USB, works with Zoom/Teams/Meet.",
        price: 2200, originalPrice: 2800, category: "Electronics", stock: 16, condition: "Used",
        images: ["https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=400&q=80"],
        tags: ["webcam", "1080p", "hd", "microphone", "online class"],
        rating: 4.4, reviewCount: 47, sold: 112, createdAt: Date.now() - 86400000 * 22,
      },
      {
        id: "prod_e18", vendorId: "vendor_001", vendorName: "TechZone RUET",
        name: "Soldering Iron Station 60W", emoji: "🔥",
        description: "Temperature-controlled soldering station 200–480°C. Includes 5 tips, solder wire, stand, and sponge. Ideal for ECE lab and project work.",
        price: 1650, originalPrice: 2100, category: "Electronics", stock: 18, condition: "New",
        images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80"],
        tags: ["soldering", "iron", "station", "ece", "lab"],
        rating: 4.6, reviewCount: 35, sold: 84, createdAt: Date.now() - 86400000 * 24,
      },
      {
        id: "prod_e19", vendorId: "vendor_001", vendorName: "TechZone RUET",
        name: "Monitor Light Bar USB Powered", emoji: "🌟",
        description: "Asymmetric lighting prevents screen glare. USB powered, touch dimmer, 3 color temperatures, mounts on any monitor. Reduces eye strain.",
        price: 1900, originalPrice: 2400, category: "Electronics", stock: 22, condition: "Used",
        images: ["https://images.unsplash.com/photo-1616763355548-1b606f439f86?w=400&q=80"],
        tags: ["monitor light", "screen bar", "eye care", "usb"],
        rating: 4.7, reviewCount: 29, sold: 61, createdAt: Date.now() - 86400000 * 26,
      },
      {
        id: "prod_e20", vendorId: "vendor_001", vendorName: "TechZone RUET",
        name: "Wireless Charging Pad 15W", emoji: "🔌",
        description: "15W fast wireless charger compatible with Qi-enabled phones. LED indicator, anti-slip surface, includes adapter. Charges through thin cases.",
        price: 950, originalPrice: 1200, category: "Electronics", stock: 40, condition: "Used",
        images: ["https://images.unsplash.com/photo-1609081219090-a6d81d3085bf?w=400&q=80"],
        tags: ["wireless charging", "qi", "fast charge", "pad"],
        rating: 4.2, reviewCount: 63, sold: 167, createdAt: Date.now() - 86400000 * 28,
      },

      // ── STATIONERY & BOOKS (20 products) ──
      {
        id: "prod_s01", vendorId: "user_003", vendorName: "Kamal Uddin",
        name: "Casio FX-991EX Classwiz Calculator", emoji: "🧮",
        description: "Used for 1.5 years. Fully functional, no scratches on screen. 552 functions including spreadsheet, QR code, complex numbers.",
        price: 650, originalPrice: 1300, category: "Stationery", stock: 1, condition: "Used",
        images: ["https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&q=80"],
        tags: ["calculator", "casio", "fx991", "scientific", "exam"],
        rating: 0, reviewCount: 0, sold: 0, createdAt: Date.now() - 86400000 * 30,
      },
      {
        id: "prod_s02", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Engineering Drawing Set (Staedtler)", emoji: "📐",
        description: "9-piece precision drawing set: compass, divider, ruling pen, extension bar, 45° and 60° triangles. In metal case. RUET engineering drawing standard.",
        price: 1200, originalPrice: 1500, category: "Stationery", stock: 30, condition: "Used",
        images: ["https://images.unsplash.com/photo-1572635148818-ef6fd45eb394?w=400&q=80"],
        tags: ["drawing set", "compass", "staedtler", "engineering drawing"],
        rating: 4.7, reviewCount: 56, sold: 142, createdAt: Date.now() - 86400000 * 28,
      },
      {
        id: "prod_s03", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "A4 80GSM Notebook (200 pages)", emoji: "📓",
        description: "Premium spiral-bound notebook, hardcover, 80GSM bright white paper, ruled. Perfect for lectures. Available in blue, red, black covers.",
        price: 240, originalPrice: 240, category: "Stationery", stock: 150, condition: "New",
        images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&q=80"],
        tags: ["notebook", "spiral", "a4", "ruled", "hardcover"],
        rating: 4.3, reviewCount: 211, sold: 678, createdAt: Date.now() - 86400000 * 26,
      },
      {
        id: "prod_s04", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Pilot G2 Gel Pen Pack (10pcs)", emoji: "✒️",
        description: "Smooth writing 0.7mm gel pens. Refillable, transparent barrel to see ink level. Black ink. Industry standard for exam use.",
        price: 450, originalPrice: 450, category: "Stationery", stock: 100, condition: "New",
        images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=400&q=80"],
        tags: ["pen", "pilot", "gel", "g2", "writing"],
        rating: 4.8, reviewCount: 175, sold: 520, createdAt: Date.now() - 86400000 * 24,
      },
      {
        id: "prod_s05", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Graph Paper Pad A3 (50 sheets)", emoji: "📏",
        description: "A3 1mm/5mm grid graph paper, 90GSM, perforated. Required for engineering drawing, data plotting, and lab reports at RUET.",
        price: 130, originalPrice: 160, category: "Stationery", stock: 120, condition: "New",
        images: ["https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&q=80"],
        tags: ["graph paper", "a3", "grid", "engineering drawing", "lab"],
        rating: 4.5, reviewCount: 89, sold: 267, createdAt: Date.now() - 86400000 * 22,
      },
      {
        id: "prod_s06", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Highlighter Set (6 colors)", emoji: "🖊️",
        description: "Chisel tip fluorescent highlighters in 6 colors. Smear-proof on most inks, cap-off protection. Ideal for textbook marking.",
        price: 280, originalPrice: 280, category: "Stationery", stock: 80, condition: "New",
        images: ["https://images.unsplash.com/photo-1604423913271-fc86c29dd4b9?w=400&q=80"],
        tags: ["highlighter", "colorful", "study", "marker"],
        rating: 4.4, reviewCount: 132, sold: 398, createdAt: Date.now() - 86400000 * 20,
      },
      {
        id: "prod_s07", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Drawing Pencil Set HB–6B (12pcs)", emoji: "✏️",
        description: "Professional graphite pencil set HB, B, 2B, 3B, 4B, 5B, 6B. Cedar wood, break-resistant core. Ideal for engineering drawing and sketching.",
        price: 280, originalPrice: 350, category: "Stationery", stock: 90, condition: "New",
        images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400&q=80"],
        tags: ["pencil", "drawing", "graphite", "sketch", "art"],
        rating: 4.6, reviewCount: 98, sold: 312, createdAt: Date.now() - 86400000 * 18,
      },
      {
        id: "prod_s08", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "A4 Presentation Folder (10pcs)", emoji: "📁",
        description: "Clear view A4 presentation folders with spine label. PP material, holds up to 30 pages. Essential for lab reports and project submissions.",
        price: 200, originalPrice: 200, category: "Stationery", stock: 200, condition: "New",
        images: ["https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400&q=80"],
        tags: ["folder", "presentation", "a4", "report", "submission"],
        rating: 4.2, reviewCount: 167, sold: 534, createdAt: Date.now() - 86400000 * 16,
      },
      {
        id: "prod_s09", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Stapler + Staples Kit (Kangaro)", emoji: "📎",
        description: "Heavy-duty desktop stapler handles up to 25 sheets. Includes 1000 staples. Non-slip base, ergonomic handle. Long-lasting and reliable.",
        price: 320, originalPrice: 400, category: "Stationery", stock: 55, condition: "Used",
        images: ["https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&q=80"],
        tags: ["stapler", "office", "kangaro", "stationery"],
        rating: 4.3, reviewCount: 72, sold: 198, createdAt: Date.now() - 86400000 * 14,
      },
      {
        id: "prod_s10", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Scientific Reference Card Set", emoji: "📊",
        description: "Laminated quick-reference cards: Math formulas, Physics constants, Chemistry periodic table, Engineering units. Waterproof, pocket-sized.",
        price: 180, originalPrice: 220, category: "Stationery", stock: 70, condition: "Used",
        images: ["https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&q=80"],
        tags: ["reference", "formula", "study", "quick reference", "exam"],
        rating: 4.7, reviewCount: 88, sold: 234, createdAt: Date.now() - 86400000 * 12,
      },
      {
        id: "prod_b01", vendorId: "user_001", vendorName: "Rahim Hossain",
        name: "Engineering Mathematics – Kreyszig", emoji: "📘",
        description: "Used for 1 semester, fully fresh pages with minor highlights. Covers ODEs, linear algebra, vector analysis, complex analysis, numerical methods.",
        price: 1200, originalPrice: 2400, category: "Books", stock: 1, condition: "Used",
        images: ["https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&q=80"],
        tags: ["textbook", "mathematics", "kreyszig", "engineering", "ode"],
        rating: 0, reviewCount: 0, sold: 0, createdAt: Date.now() - 86400000 * 32,
      },
      {
        id: "prod_b02", vendorId: "user_002", vendorName: "Sumaiya Begum",
        name: "Introduction to Algorithms – CLRS", emoji: "📗",
        description: "Used for 2 semesters, cover slightly bent but completely readable. The definitive textbook for algorithms and data structures. Essential for CSE/ICE.",
        price: 1500, originalPrice: 3000, category: "Books", stock: 1, condition: "Used",
        images: ["https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&q=80"],
        tags: ["textbook", "algorithms", "clrs", "cse", "programming"],
        rating: 0, reviewCount: 0, sold: 0, createdAt: Date.now() - 86400000 * 30,
      },
      {
        id: "prod_b03", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Digital Logic & Computer Design – Mano", emoji: "📙",
        description: "Morris Mano's classic textbook on digital circuits, Boolean algebra, sequential logic, flip-flops, and computer organization.",
        price: 1400, originalPrice: 1800, category: "Books", stock: 25, condition: "Used",
        images: ["https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400&q=80"],
        tags: ["textbook", "digital logic", "cse", "eee", "computer design"],
        rating: 4.7, reviewCount: 53, sold: 108, createdAt: Date.now() - 86400000 * 28,
      },
      {
        id: "prod_b04", vendorId: "user_003", vendorName: "Kamal Uddin",
        name: "Clean Code – Robert C. Martin", emoji: "📕",
        description: "Used for 3 months, fully fresh like new condition. Learn to write maintainable, readable, professional code. Must-read for every CS student.",
        price: 1000, originalPrice: 2000, category: "Books", stock: 1, condition: "Used",
        images: ["https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&q=80"],
        tags: ["textbook", "programming", "clean code", "software engineering"],
        rating: 0, reviewCount: 0, sold: 0, createdAt: Date.now() - 86400000 * 26,
      },
      {
        id: "prod_b05", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Fluid Mechanics – Frank White (8th Ed)", emoji: "📘",
        description: "Comprehensive fluid mechanics textbook. Covers pressure, flow, viscosity, Bernoulli, pipe flow, turbomachinery. Standard for ME/CE students.",
        price: 1900, originalPrice: 2500, category: "Books", stock: 12, condition: "Used",
        images: ["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80"],
        tags: ["textbook", "fluid mechanics", "me", "ce", "frank white"],
        rating: 4.6, reviewCount: 29, sold: 58, createdAt: Date.now() - 86400000 * 24,
      },
      {
        id: "prod_b06", vendorId: "user_001", vendorName: "Rahim Hossain",
        name: "Circuit Analysis – Hayt & Kemmerly", emoji: "📗",
        description: "Used for 1 semester, a little fault on the spine but pages are fresh. Engineering Circuit Analysis, 8th Edition. Covers DC/AC circuits, Laplace.",
        price: 900, originalPrice: 2200, category: "Books", stock: 1, condition: "Used",
        images: ["https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=400&q=80"],
        tags: ["textbook", "circuit analysis", "eee", "ece", "hayt"],
        rating: 0, reviewCount: 0, sold: 0, createdAt: Date.now() - 86400000 * 22,
      },
      {
        id: "prod_b07", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Probability & Statistics for Engineers", emoji: "📙",
        description: "Walpole, Myers & Myers. Covers probability, distributions, estimation, hypothesis testing, regression. Required for 3rd year engineers.",
        price: 1500, originalPrice: 2000, category: "Books", stock: 22, condition: "Used",
        images: ["https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400&q=80"],
        tags: ["textbook", "probability", "statistics", "walpole", "math"],
        rating: 4.5, reviewCount: 51, sold: 102, createdAt: Date.now() - 86400000 * 20,
      },
      {
        id: "prod_b08", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Data Structures in C++ (Malik)", emoji: "📕",
        description: "D.S. Malik's Data Structures Using C++. Arrays, linked lists, stacks, queues, trees, graphs, sorting & searching. Great for programming lab.",
        price: 1300, originalPrice: 1700, category: "Books", stock: 28, condition: "Used",
        images: ["https://images.unsplash.com/photo-1550399105-c4db5fb85c18?w=400&q=80"],
        tags: ["textbook", "data structures", "c++", "programming", "cse"],
        rating: 4.6, reviewCount: 63, sold: 127, createdAt: Date.now() - 86400000 * 18,
      },
      {
        id: "prod_b09", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Thermodynamics – Cengel & Boles", emoji: "📘",
        description: "Thermodynamics: An Engineering Approach, 9th Edition. Laws of thermodynamics, cycles, refrigeration, psychrometrics. Standard ME textbook.",
        price: 2000, originalPrice: 2600, category: "Books", stock: 14, condition: "Used",
        images: ["https://images.unsplash.com/photo-1416339442236-8ceb164046f8?w=400&q=80"],
        tags: ["textbook", "thermodynamics", "me", "cengel", "engineering"],
        rating: 4.7, reviewCount: 35, sold: 70, createdAt: Date.now() - 86400000 * 16,
      },
      {
        id: "prod_b10", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Soil Mechanics – Das (10th Ed)", emoji: "📗",
        description: "Braja M. Das, Principles of Foundation Engineering. Soil classification, compaction, consolidation, shear strength, foundations. CE standard.",
        price: 1800, originalPrice: 2300, category: "Books", stock: 17, condition: "New",
        images: ["https://images.unsplash.com/photo-1589998059171-988d887df646?w=400&q=80"],
        tags: ["textbook", "soil mechanics", "ce", "civil engineering", "das"],
        rating: 4.6, reviewCount: 28, sold: 56, createdAt: Date.now() - 86400000 * 14,
      },

      // ── CLOTHING (15 products) ──
      {
        id: "prod_c01", vendorId: "vendor_003", vendorName: "RUET Fashion Hub",
        name: "RUET Premium Polo T-Shirt", emoji: "👕",
        description: "100% pique cotton polo with embroidered RUET logo. Available S, M, L, XL, XXL. Navy blue & white options. Ideal for campus events.",
        price: 750, originalPrice: 750, category: "Clothing", stock: 80, condition: "New",
        images: ["https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=400&q=80"],
        tags: ["polo", "ruet", "cotton", "t-shirt", "campus wear"],
        rating: 4.7, reviewCount: 145, sold: 432, createdAt: Date.now() - 86400000 * 34,
      },
      {
        id: "prod_c02", vendorId: "vendor_003", vendorName: "RUET Fashion Hub",
        name: "RUET Hoodie (Winter Fleece)", emoji: "🧥",
        description: "Thick fleece hoodie with RUET logo print. Kangaroo pocket, adjustable drawstring, ribbed cuffs. Sizes S–XXL. Perfect for cold hostel nights.",
        price: 1600, originalPrice: 1600, category: "Clothing", stock: 45, condition: "New",
        images: ["https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=400&q=80"],
        tags: ["hoodie", "ruet", "fleece", "winter", "campus"],
        rating: 4.8, reviewCount: 89, sold: 267, createdAt: Date.now() - 86400000 * 32,
      },
      {
        id: "prod_c03", vendorId: "vendor_003", vendorName: "RUET Fashion Hub",
        name: "Formal Dress Shirt (White, Slim Fit)", emoji: "👔",
        description: "Crisp white formal shirt, slim fit, cotton-polyester blend. French cuffs, spread collar. Ideal for viva, industrial visits, and presentations.",
        price: 950, originalPrice: 950, category: "Clothing", stock: 60, condition: "New",
        images: ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&q=80"],
        tags: ["shirt", "formal", "white", "slim fit", "viva"],
        rating: 4.5, reviewCount: 112, sold: 298, createdAt: Date.now() - 86400000 * 30,
      },
      {
        id: "prod_c04", vendorId: "user_002", vendorName: "Sumaiya Begum",
        name: "Lab Coat (White, Unisex)", emoji: "🥼",
        description: "Used for 1 semester. Washed and fully fresh, no stains. Standard white lab coat for chemistry and biology labs. 100% cotton, two pockets.",
        price: 350, originalPrice: 850, category: "Clothing", stock: 1, condition: "Like New",
        images: ["https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=400&q=80"],
        tags: ["lab coat", "white", "lab", "chemistry", "safety"],
        rating: 0, reviewCount: 0, sold: 0, createdAt: Date.now() - 86400000 * 28,
      },
      {
        id: "prod_c05", vendorId: "vendor_003", vendorName: "RUET Fashion Hub",
        name: "Cargo Pants (Multi-Pocket)", emoji: "👖",
        description: "Durable cotton cargo pants with 6 pockets. Straight fit, reinforced stitching. Available in khaki, olive, and black. Great for fieldwork.",
        price: 950, originalPrice: 1200, category: "Clothing", stock: 50, condition: "New",
        images: ["https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&q=80"],
        tags: ["cargo pants", "multi-pocket", "fieldwork", "durable"],
        rating: 4.4, reviewCount: 76, sold: 189, createdAt: Date.now() - 86400000 * 26,
      },
      {
        id: "prod_c06", vendorId: "vendor_003", vendorName: "RUET Fashion Hub",
        name: "Sports Shorts (Dri-Fit)", emoji: "🩳",
        description: "Moisture-wicking dri-fit shorts. Elastic waistband, drawstring, side pockets. Ideal for morning exercise, sports, and casual campus wear.",
        price: 480, originalPrice: 480, category: "Clothing", stock: 90, condition: "New",
        images: ["https://images.unsplash.com/photo-1562183241-b937e9102f0d?w=400&q=80"],
        tags: ["shorts", "sports", "dri-fit", "exercise", "casual"],
        rating: 4.3, reviewCount: 134, sold: 378, createdAt: Date.now() - 86400000 * 24,
      },
      {
        id: "prod_c07", vendorId: "vendor_003", vendorName: "RUET Fashion Hub",
        name: "Winter Jacket (Puffer, Lightweight)", emoji: "🧥",
        description: "Lightweight puffer jacket with synthetic fill. Water-resistant shell, zip pockets, elastic cuffs. Packable into its own pocket.",
        price: 2400, originalPrice: 2400, category: "Clothing", stock: 30, condition: "New",
        images: ["https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=400&q=80"],
        tags: ["jacket", "puffer", "winter", "lightweight", "water resistant"],
        rating: 4.6, reviewCount: 67, sold: 145, createdAt: Date.now() - 86400000 * 22,
      },
      {
        id: "prod_c08", vendorId: "user_001", vendorName: "Rahim Hossain",
        name: "Canvas Sneakers (Unisex)", emoji: "👟",
        description: "Bought the wrong size online. Completely unworn and brand new. Classic low-top canvas sneakers with rubber sole. Size 42.",
        price: 1600, originalPrice: 1600, category: "Clothing", stock: 1, condition: "New",
        images: ["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=400&q=80"],
        tags: ["sneakers", "canvas", "unisex", "shoes", "casual"],
        rating: 0, reviewCount: 0, sold: 0, createdAt: Date.now() - 86400000 * 20,
      },
      {
        id: "prod_c09", vendorId: "user_003", vendorName: "Kamal Uddin",
        name: "Backpack 30L (Waterproof)", emoji: "🎒",
        description: "Used for 1 year. One minor tear inside, but zips work perfectly. 30L student backpack with laptop compartment (up to 15.6\").",
        price: 800, originalPrice: 2100, category: "Clothing", stock: 1, condition: "Used",
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80"],
        tags: ["backpack", "waterproof", "laptop bag", "30l", "student"],
        rating: 0, reviewCount: 0, sold: 0, createdAt: Date.now() - 86400000 * 18,
      },
      {
        id: "prod_c10", vendorId: "vendor_003", vendorName: "RUET Fashion Hub",
        name: "Sandal (Comfort Sole, Leather)", emoji: "👡",
        description: "Genuine leather upper sandal with memory foam footbed. Adjustable straps, anti-slip rubber sole. Lightweight, ideal for daily campus use.",
        price: 1100, originalPrice: 1100, category: "Clothing", stock: 55, condition: "New",
        images: ["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&q=80"],
        tags: ["sandal", "leather", "comfort", "daily wear", "campus"],
        rating: 4.4, reviewCount: 78, sold: 189, createdAt: Date.now() - 86400000 * 16,
      },
      {
        id: "prod_c11", vendorId: "vendor_003", vendorName: "RUET Fashion Hub",
        name: "Prayer Cap (Taqiyah) – White", emoji: "🕌",
        description: "Soft white crocheted taqiyah prayer cap. Breathable cotton, one size fits most. Machine washable. Essential for Friday prayers.",
        price: 150, originalPrice: 150, category: "Clothing", stock: 200, condition: "New",
        images: ["https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=400&q=80"],
        tags: ["prayer cap", "taqiyah", "white", "religious", "cotton"],
        rating: 4.6, reviewCount: 234, sold: 712, createdAt: Date.now() - 86400000 * 14,
      },
      {
        id: "prod_c12", vendorId: "vendor_003", vendorName: "RUET Fashion Hub",
        name: "Polo T-Shirt Pack (3pcs, Plain)", emoji: "👕",
        description: "Pack of 3 plain polo shirts in 3 different colors. 100% cotton pique, ribbed collar and cuffs. Comfortable for everyday campus wear.",
        price: 1650, originalPrice: 1650, category: "Clothing", stock: 50, condition: "New",
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a45?w=400&q=80"],
        tags: ["polo", "pack", "cotton", "3 in 1", "plain"],
        rating: 4.5, reviewCount: 91, sold: 234, createdAt: Date.now() - 86400000 * 12,
      },
      {
        id: "prod_c13", vendorId: "vendor_003", vendorName: "RUET Fashion Hub",
        name: "Sports Socks Pack (5 pairs)", emoji: "🧦",
        description: "Cotton-spandex sports socks with cushioned sole and arch support. Moisture-wicking, anti-blister. Fits shoe sizes 39–44.",
        price: 350, originalPrice: 350, category: "Clothing", stock: 120, condition: "New",
        images: ["https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=400&q=80"],
        tags: ["socks", "sports", "pack", "cotton", "anti-blister"],
        rating: 4.3, reviewCount: 167, sold: 498, createdAt: Date.now() - 86400000 * 10,
      },
      {
        id: "prod_c14", vendorId: "vendor_003", vendorName: "RUET Fashion Hub",
        name: "Jeans (Slim Fit, Stretch Denim)", emoji: "👖",
        description: "Slim-fit stretch denim jeans. 98% cotton, 2% elastane, mid-rise waist. Available in light, medium, and dark wash. Sizes 28–38.",
        price: 1800, originalPrice: 1800, category: "Clothing", stock: 45, condition: "New",
        images: ["https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&q=80"],
        tags: ["jeans", "slim fit", "denim", "stretch", "casual"],
        rating: 4.5, reviewCount: 83, sold: 201, createdAt: Date.now() - 86400000 * 8,
      },
      {
        id: "prod_c15", vendorId: "vendor_003", vendorName: "RUET Fashion Hub",
        name: "Sunglasses (UV400 Polarized)", emoji: "🕶️",
        description: "Polarized UV400 sunglasses with metal frame and TR90 temples. Reduces glare by 99%. Lightweight at 28g. Comes with hard case and cloth.",
        price: 900, originalPrice: 900, category: "Clothing", stock: 60, condition: "New",
        images: ["https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400&q=80"],
        tags: ["sunglasses", "polarized", "uv400", "outdoor", "fashion"],
        rating: 4.4, reviewCount: 56, sold: 134, createdAt: Date.now() - 86400000 * 6,
      },

      // ── FOOD & BEVERAGES (15 products) ──
      {
        id: "prod_f01", vendorId: "vendor_004", vendorName: "Campus Canteen Supplies",
        name: "Nescafé Classic Instant Coffee 200g", emoji: "☕",
        description: "Nescafé Classic 200g jar. Rich aroma, smooth taste. Perfect for late-night study sessions. Makes approximately 100+ cups.",
        price: 580, originalPrice: 580, category: "Food", stock: 60, condition: "New",
        images: ["https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&q=80"],
        tags: ["coffee", "nescafe", "instant", "study", "caffeine"],
        rating: 4.7, reviewCount: 189, sold: 567, createdAt: Date.now() - 86400000 * 14,
      },
      {
        id: "prod_f02", vendorId: "vendor_004", vendorName: "Campus Canteen Supplies",
        name: "Maggi Masala Noodles Pack (12)", emoji: "🍜",
        description: "12-pack of Maggi 2-minute masala noodles. 70g each. The ultimate hostel meal. Quick to prepare, great taste. Hall room essential.",
        price: 420, originalPrice: 420, category: "Food", stock: 100, condition: "New",
        images: ["https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&q=80"],
        tags: ["noodles", "maggi", "instant", "hostel", "snack"],
        rating: 4.5, reviewCount: 312, sold: 1045, createdAt: Date.now() - 86400000 * 12,
      },
      {
        id: "prod_f03", vendorId: "vendor_004", vendorName: "Campus Canteen Supplies",
        name: "Red Bull Energy Drink Pack (6×250ml)", emoji: "⚡",
        description: "6 cans of Red Bull 250ml. Vitalizes body and mind with taurine, B-vitamins, and caffeine. Perfect for all-night exam prep sessions.",
        price: 900, originalPrice: 900, category: "Food", stock: 50, condition: "New",
        images: ["https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=400&q=80"],
        tags: ["energy drink", "red bull", "caffeine", "exam", "pack"],
        rating: 4.3, reviewCount: 134, sold: 389, createdAt: Date.now() - 86400000 * 10,
      },
      {
        id: "prod_f04", vendorId: "vendor_004", vendorName: "Campus Canteen Supplies",
        name: "Horlicks Chocolate 500g", emoji: "🍫",
        description: "Horlicks Chocolate flavored malted milk drink. Rich in Vitamin D, B2, B12, iron and zinc. A nourishing drink for growing students.",
        price: 520, originalPrice: 520, category: "Food", stock: 45, condition: "New",
        images: ["https://images.unsplash.com/photo-1543362906-acfc16c67564?w=400&q=80"],
        tags: ["horlicks", "chocolate", "malt", "health drink", "nutrition"],
        rating: 4.6, reviewCount: 98, sold: 276, createdAt: Date.now() - 86400000 * 8,
      },
      {
        id: "prod_f05", vendorId: "vendor_004", vendorName: "Campus Canteen Supplies",
        name: "Mixed Nuts Trail Mix 500g", emoji: "🥜",
        description: "Premium mix of cashews, almonds, raisins, dried cranberries, and pumpkin seeds. Rich in protein and healthy fats. Great study snack.",
        price: 850, originalPrice: 850, category: "Food", stock: 35, condition: "New",
        images: ["https://images.unsplash.com/photo-1536816579748-4ecb3f03d72a?w=400&q=80"],
        tags: ["nuts", "trail mix", "healthy", "snack", "protein"],
        rating: 4.7, reviewCount: 76, sold: 198, createdAt: Date.now() - 86400000 * 6,
      },
      {
        id: "prod_f06", vendorId: "vendor_004", vendorName: "Campus Canteen Supplies",
        name: "Dates Khejur (Premium, 500g)", emoji: "🌴",
        description: "Premium Medjool-style dates, soft and sweet. Rich in fiber, potassium, and natural sugars. Great energy boost. Sourced from Rajshahi.",
        price: 480, originalPrice: 480, category: "Food", stock: 40, condition: "New",
        images: ["https://images.unsplash.com/photo-1562157854-ef3d6c65c40e?w=400&q=80"],
        tags: ["dates", "khejur", "natural", "healthy", "energy"],
        rating: 4.8, reviewCount: 112, sold: 334, createdAt: Date.now() - 86400000 * 4,
      },
      {
        id: "prod_f07", vendorId: "vendor_004", vendorName: "Campus Canteen Supplies",
        name: "Pran Chanachur Masala (250g)", emoji: "🌶️",
        description: "Spicy fried lentil and nut mix with authentic Bengali masala seasoning. Crispy, flavorful tea-time snack. Popular among RUET students.",
        price: 145, originalPrice: 145, category: "Food", stock: 150, condition: "New",
        images: ["https://images.unsplash.com/photo-1548010757-8c5d8d8d0c8d?w=400&q=80"],
        tags: ["chanachur", "pran", "snack", "spicy", "bengali"],
        rating: 4.5, reviewCount: 278, sold: 892, createdAt: Date.now() - 86400000 * 3,
      },
      {
        id: "prod_f08", vendorId: "vendor_004", vendorName: "Campus Canteen Supplies",
        name: "Protein Shake Powder 1kg (Vanilla)", emoji: "💪",
        description: "Whey protein isolate 24g per serving. 1kg (33 servings). Low fat, low sugar, good for muscle recovery after sports. Vanilla flavor.",
        price: 3500, originalPrice: 3500, category: "Food", stock: 20, condition: "New",
        images: ["https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400&q=80"],
        tags: ["protein", "whey", "supplement", "fitness", "muscle"],
        rating: 4.6, reviewCount: 45, sold: 89, createdAt: Date.now() - 86400000 * 22,
      },
      {
        id: "prod_f09", vendorId: "vendor_004", vendorName: "Campus Canteen Supplies",
        name: "Biscuit Assortment Tin (600g)", emoji: "🍪",
        description: "Premium biscuit assortment: marie, cream crackers, butter biscuits, chocolate chip. 600g tin, resealable lid. Great for sharing in hall.",
        price: 560, originalPrice: 560, category: "Food", stock: 55, condition: "New",
        images: ["https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&q=80"],
        tags: ["biscuit", "assortment", "snack", "tin", "sharing"],
        rating: 4.4, reviewCount: 134, sold: 367, createdAt: Date.now() - 86400000 * 20,
      },
      {
        id: "prod_f10", vendorId: "vendor_004", vendorName: "Campus Canteen Supplies",
        name: "Green Tea Bags (100 bags)", emoji: "🍵",
        description: "Premium green tea bags, individually wrapped. Rich in antioxidants, L-theanine for calm focus. Ideal for late-night study sessions.",
        price: 320, originalPrice: 400, category: "Food", stock: 80, condition: "New",
        images: ["https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80"],
        tags: ["green tea", "tea bags", "antioxidant", "health", "study"],
        rating: 4.7, reviewCount: 156, sold: 467, createdAt: Date.now() - 86400000 * 18,
      },
      {
        id: "prod_f11", vendorId: "vendor_004", vendorName: "Campus Canteen Supplies",
        name: "Mineral Water Bottle 1.5L (6-pack)", emoji: "💧",
        description: "6 × 1.5L mineral water bottles. pH balanced, fluoride-free. Stay hydrated during classes and exams. Reusable-grade PET bottles.",
        price: 300, originalPrice: 300, category: "Food", stock: 200, condition: "New",
        images: ["https://images.unsplash.com/photo-1523362628745-0c100150b504?w=400&q=80"],
        tags: ["water", "mineral", "hydration", "pack", "healthy"],
        rating: 4.2, reviewCount: 445, sold: 1345, createdAt: Date.now() - 86400000 * 16,
      },
      {
        id: "prod_f12", vendorId: "vendor_004", vendorName: "Campus Canteen Supplies",
        name: "Oatmeal Instant Sachets (10pcs)", emoji: "🥣",
        description: "Instant oatmeal sachets, 35g each. High fiber, heart-healthy. Just add hot water. Available in apple cinnamon and banana flavors.",
        price: 350, originalPrice: 350, category: "Food", stock: 90, condition: "New",
        images: ["https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=400&q=80"],
        tags: ["oatmeal", "instant", "breakfast", "healthy", "fiber"],
        rating: 4.5, reviewCount: 87, sold: 234, createdAt: Date.now() - 86400000 * 14,
      },
      {
        id: "prod_f13", vendorId: "vendor_004", vendorName: "Campus Canteen Supplies",
        name: "Multivitamin Tablets (30 days)", emoji: "💊",
        description: "Complete daily multivitamin with 23 vitamins and minerals including Vitamin C, D, B12, Zinc. Immune support + energy boost for students.",
        price: 720, originalPrice: 720, category: "Food", stock: 40, condition: "New",
        images: ["https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80"],
        tags: ["vitamin", "supplement", "health", "immunity", "daily"],
        rating: 4.6, reviewCount: 67, sold: 178, createdAt: Date.now() - 86400000 * 12,
      },
      {
        id: "prod_f14", vendorId: "vendor_004", vendorName: "Campus Canteen Supplies",
        name: "Dark Chocolate Bar 70% (Pack of 5)", emoji: "🍫",
        description: "5 × 70g dark chocolate bars, 70% cocoa. Rich in flavonoids and antioxidants. Studies show dark chocolate improves focus and mood.",
        price: 480, originalPrice: 600, category: "Food", stock: 65, condition: "New",
        images: ["https://images.unsplash.com/photo-1548741487-18d363dc4469?w=400&q=80"],
        tags: ["chocolate", "dark", "cocoa", "snack", "antioxidant"],
        rating: 4.8, reviewCount: 143, sold: 398, createdAt: Date.now() - 86400000 * 10,
      },
      {
        id: "prod_f15", vendorId: "vendor_004", vendorName: "Campus Canteen Supplies",
        name: "Coffee Thermos Flask 500ml", emoji: "🫙",
        description: "Double-wall vacuum insulated stainless steel thermos. Keeps hot 12h, cold 24h. Leak-proof, BPA-free, fits standard cup holders.",
        price: 1100, originalPrice: 1100, category: "Food", stock: 50, condition: "New",
        images: ["https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=400&q=80"],
        tags: ["thermos", "flask", "insulated", "coffee", "travel"],
        rating: 4.7, reviewCount: 98, sold: 256, createdAt: Date.now() - 86400000 * 8,
      },

      // ── LAB SUPPLIES (15 products) ──
      {
        id: "prod_l01", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Safety Goggles (Anti-Fog, ANSI Z87)", emoji: "🥽",
        description: "ANSI Z87.1 rated clear polycarbonate goggles. Anti-fog coating, UV protection, indirect ventilation. Required for chemistry and physics labs.",
        price: 280, originalPrice: 360, category: "Lab Supplies", stock: 60, condition: "Used",
        images: ["https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?w=400&q=80"],
        tags: ["goggles", "safety", "ansi", "lab", "chemistry"],
        rating: 4.5, reviewCount: 112, sold: 334, createdAt: Date.now() - 86400000 * 30,
      },
      {
        id: "prod_l02", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Nitrile Gloves (100pcs, Medium)", emoji: "🧤",
        description: "Powder-free nitrile examination gloves, 4mil thick. Latex-free, chemical-resistant, textured fingertips for grip. Box of 100 in medium size.",
        price: 480, originalPrice: 600, category: "Lab Supplies", stock: 50, condition: "Used",
        images: ["https://images.unsplash.com/photo-1584556812952-905ffd0c611a?w=400&q=80"],
        tags: ["gloves", "nitrile", "lab", "disposable", "safety"],
        rating: 4.6, reviewCount: 87, sold: 234, createdAt: Date.now() - 86400000 * 28,
      },
      {
        id: "prod_l03", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Vernier Caliper 150mm (Digital)", emoji: "📏",
        description: "Digital vernier caliper 0–150mm with 0.01mm resolution. LCD display, auto-off, mm/inch switch. Stainless steel, with protective case.",
        price: 650, originalPrice: 820, category: "Lab Supplies", stock: 35, condition: "New",
        images: ["https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400&q=80"],
        tags: ["caliper", "vernier", "digital", "measurement", "precision"],
        rating: 4.7, reviewCount: 78, sold: 198, createdAt: Date.now() - 86400000 * 26,
      },
      {
        id: "prod_l04", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Oscilloscope Probe Kit (1×/10×)", emoji: "📡",
        description: "Professional oscilloscope probes 1× and 10× attenuation. BNC connector, 60MHz bandwidth, 1.2m cable. Compatible with most oscilloscopes.",
        price: 1200, originalPrice: 1500, category: "Lab Supplies", stock: 20, condition: "Used",
        images: ["https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&q=80"],
        tags: ["oscilloscope", "probe", "eee", "ece", "lab"],
        rating: 4.6, reviewCount: 34, sold: 67, createdAt: Date.now() - 86400000 * 24,
      },
      {
        id: "prod_l05", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Breadboard 830 Tie-Points + Jumper Kit", emoji: "🔌",
        description: "Full-size 830 tie-point breadboard + 140pcs jumper wires (male-to-male, male-to-female, female-to-female). Essential for circuit experiments.",
        price: 380, originalPrice: 480, category: "Lab Supplies", stock: 55, condition: "New",
        images: ["https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=80"],
        tags: ["breadboard", "jumper wires", "circuit", "eee", "prototype"],
        rating: 4.8, reviewCount: 134, sold: 412, createdAt: Date.now() - 86400000 * 22,
      },
      {
        id: "prod_l06", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Chemistry Lab Apron (Acid-Resistant)", emoji: "🧪",
        description: "PVC-coated acid-resistant lab apron. Full coverage, adjustable neck and waist ties. Protects against splashes of chemicals. Wipe-clean.",
        price: 350, originalPrice: 440, category: "Lab Supplies", stock: 45, condition: "New",
        images: ["https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=400&q=80"],
        tags: ["apron", "lab", "acid resistant", "chemistry", "safety"],
        rating: 4.4, reviewCount: 56, sold: 145, createdAt: Date.now() - 86400000 * 20,
      },
      {
        id: "prod_l07", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Electronic Component Starter Kit", emoji: "🔩",
        description: "600+ components: resistors, capacitors, LEDs, transistors, diodes, potentiometers, IC sockets, push buttons. Organized in compartment box.",
        price: 1400, originalPrice: 1800, category: "Lab Supplies", stock: 25, condition: "New",
        images: ["https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=80"],
        tags: ["components", "electronics kit", "resistors", "capacitors", "ece"],
        rating: 4.9, reviewCount: 89, sold: 223, createdAt: Date.now() - 86400000 * 18,
      },
      {
        id: "prod_l08", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Micrometer Screw Gauge 0–25mm", emoji: "🔍",
        description: "Outside micrometer 0–25mm, 0.001mm resolution. Hardened steel anvil and spindle, ratchet thimble, lock nut. For precision ME labs.",
        price: 950, originalPrice: 1200, category: "Lab Supplies", stock: 18, condition: "New",
        images: ["https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400&q=80"],
        tags: ["micrometer", "screw gauge", "measurement", "precision", "me"],
        rating: 4.7, reviewCount: 43, sold: 89, createdAt: Date.now() - 86400000 * 16,
      },
      {
        id: "prod_l09", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "pH Meter Digital (0.01 Resolution)", emoji: "🧫",
        description: "Digital pH meter with ATC (automatic temperature compensation), 0.01 resolution, 0–14 pH range. For chemistry and environmental labs.",
        price: 1800, originalPrice: 2300, category: "Lab Supplies", stock: 12, condition: "Used",
        images: ["https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=400&q=80"],
        tags: ["ph meter", "digital", "chemistry", "lab", "measurement"],
        rating: 4.6, reviewCount: 28, sold: 56, createdAt: Date.now() - 86400000 * 14,
      },
      {
        id: "prod_l10", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Solder Wire (60/40) 100g Spool", emoji: "🔧",
        description: "60/40 tin/lead rosin-core solder wire, 1mm diameter, 100g spool. Clean flux, excellent flow, minimal splatter. For electronics lab work.",
        price: 350, originalPrice: 440, category: "Lab Supplies", stock: 60, condition: "Used",
        images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80"],
        tags: ["solder", "60/40", "electronics", "lab", "soldering"],
        rating: 4.5, reviewCount: 98, sold: 287, createdAt: Date.now() - 86400000 * 12,
      },
      {
        id: "prod_l11", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Wire Stripper & Cutter Plier", emoji: "✂️",
        description: "Professional wire stripper for 10–22 AWG. Spring-loaded, ergonomic grip, built-in cutter. Essential tool for EEE/ECE project work.",
        price: 420, originalPrice: 530, category: "Lab Supplies", stock: 40, condition: "New",
        images: ["https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400&q=80"],
        tags: ["wire stripper", "cutter", "plier", "tool", "eee"],
        rating: 4.7, reviewCount: 67, sold: 167, createdAt: Date.now() - 86400000 * 10,
      },
      {
        id: "prod_l12", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Lab Report Binder (A4, Ring Binder)", emoji: "📋",
        description: "A4 4-ring binder, 50mm capacity (~400 sheets). Clear front pocket, durable PP cover, smooth ring mechanism. For organizing lab reports.",
        price: 280, originalPrice: 350, category: "Lab Supplies", stock: 80, condition: "Used",
        images: ["https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400&q=80"],
        tags: ["binder", "ring binder", "lab report", "a4", "organizer"],
        rating: 4.3, reviewCount: 145, sold: 423, createdAt: Date.now() - 86400000 * 8,
      },
      {
        id: "prod_l13", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "PCB Etching Kit (DIY)", emoji: "⚡",
        description: "Complete PCB etching kit: ferric chloride, photoresist spray, UV lamp, developer, etchant tray, gloves. For CSE/EEE project PCB making.",
        price: 1200, originalPrice: 1600, category: "Lab Supplies", stock: 15, condition: "Used",
        images: ["https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=80"],
        tags: ["pcb", "etching", "diy", "circuit board", "ece"],
        rating: 4.8, reviewCount: 34, sold: 67, createdAt: Date.now() - 86400000 * 6,
      },
      {
        id: "prod_l14", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Thermometer Digital (Non-Contact)", emoji: "🌡️",
        description: "Non-contact IR thermometer, -50 to 380°C range, 0.5°C accuracy. Laser pointer, LCD backlight. Useful for thermal and ME lab experiments.",
        price: 780, originalPrice: 980, category: "Lab Supplies", stock: 25, condition: "New",
        images: ["https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&q=80"],
        tags: ["thermometer", "infrared", "non-contact", "lab", "temperature"],
        rating: 4.6, reviewCount: 52, sold: 123, createdAt: Date.now() - 86400000 * 4,
      },
      {
        id: "prod_l15", vendorId: "vendor_002", vendorName: "Campus Stationery",
        name: "Resistor Kit (1/4W, 500pcs, 50 values)", emoji: "🔩",
        description: "500 resistors across 50 common values (1Ω–10MΩ), 1/4W 5% tolerance. Organized in sorted component box. Essential for circuit labs.",
        price: 320, originalPrice: 400, category: "Lab Supplies", stock: 50, condition: "New",
        images: ["https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=80"],
        tags: ["resistors", "kit", "1/4w", "electronics", "components"],
        rating: 4.8, reviewCount: 112, sold: 334, createdAt: Date.now() - 86400000 * 2,
      },

      // ── SPORTS & FITNESS (10 products) ──
      {
        id: "prod_sp01", vendorId: "vendor_003", vendorName: "RUET Fashion Hub",
        name: "Cricket Bat (Kashmir Willow, Full Size)", emoji: "🏏",
        description: "Full-size Kashmir willow cricket bat, Grade 3, 1150–1200g. Medium blade, good pickup. Ready for net practice and inter-hall tournaments.",
        price: 1800, originalPrice: 2400, category: "Sports", stock: 15, condition: "Used",
        images: ["https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=400&q=80"],
        tags: ["cricket", "bat", "kashmir willow", "sports", "tournament"],
        rating: 4.6, reviewCount: 45, sold: 89, createdAt: Date.now() - 86400000 * 25,
      },
      {
        id: "prod_sp02", vendorId: "vendor_003", vendorName: "RUET Fashion Hub",
        name: "Football (Size 5, Match Quality)", emoji: "⚽",
        description: "FIFA-quality PU leather football, size 5. Hand-stitched, 32-panel design. Great for inter-hall football matches at RUET ground.",
        price: 1200, originalPrice: 1600, category: "Sports", stock: 20, condition: "Used",
        images: ["https://images.unsplash.com/photo-1552667466-07770ae110d0?w=400&q=80"],
        tags: ["football", "soccer", "size 5", "match", "outdoor"],
        rating: 4.5, reviewCount: 67, sold: 134, createdAt: Date.now() - 86400000 * 22,
      },
      {
        id: "prod_sp03", vendorId: "vendor_003", vendorName: "RUET Fashion Hub",
        name: "Badminton Racket Set (2 Rackets + Shuttles)", emoji: "🏸",
        description: "2 lightweight aluminum badminton rackets + 6 feather shuttlecocks in carry bag. Good for recreational play. Suitable for beginners.",
        price: 950, originalPrice: 1200, category: "Sports", stock: 25, condition: "Used",
        images: ["https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=400&q=80"],
        tags: ["badminton", "racket", "set", "shuttlecock", "recreation"],
        rating: 4.3, reviewCount: 89, sold: 212, createdAt: Date.now() - 86400000 * 20,
      },
      {
        id: "prod_sp04", vendorId: "vendor_003", vendorName: "RUET Fashion Hub",
        name: "Yoga Mat (Non-Slip, 6mm, 183cm)", emoji: "🧘",
        description: "6mm thick TPE yoga mat, 183×61cm. Non-slip, eco-friendly, sweat-resistant. Includes carry strap. For morning yoga and stretching routines.",
        price: 950, originalPrice: 1200, category: "Sports", stock: 30, condition: "New",
        images: ["https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80"],
        tags: ["yoga mat", "non-slip", "fitness", "exercise", "stretching"],
        rating: 4.7, reviewCount: 78, sold: 189, createdAt: Date.now() - 86400000 * 18,
      },
      {
        id: "prod_sp05", vendorId: "vendor_003", vendorName: "RUET Fashion Hub",
        name: "Resistance Bands Set (5 levels)", emoji: "💪",
        description: "Set of 5 resistance bands (10–40 lbs). Latex-free, durable, color-coded by resistance. For home workouts, stretching, and physical therapy.",
        price: 580, originalPrice: 750, category: "Sports", stock: 45, condition: "Used",
        images: ["https://images.unsplash.com/photo-1598971457999-ca4ef48a9a71?w=400&q=80"],
        tags: ["resistance bands", "workout", "fitness", "exercise", "gym"],
        rating: 4.6, reviewCount: 112, sold: 278, createdAt: Date.now() - 86400000 * 16,
      },
      {
        id: "prod_sp06", vendorId: "vendor_003", vendorName: "RUET Fashion Hub",
        name: "Jump Rope (Speed, Ball Bearings)", emoji: "🤸",
        description: "Speed jump rope with 360° ball bearing handles. Adjustable length 2.8m, PVC rope. Great for cardio and warm-up exercises.",
        price: 320, originalPrice: 400, category: "Sports", stock: 60, condition: "New",
        images: ["https://images.unsplash.com/photo-1434682772747-f16d3ea162c3?w=400&q=80"],
        tags: ["jump rope", "speed", "cardio", "fitness", "workout"],
        rating: 4.5, reviewCount: 98, sold: 267, createdAt: Date.now() - 86400000 * 14,
      },
      {
        id: "prod_sp07", vendorId: "vendor_003", vendorName: "RUET Fashion Hub",
        name: "Water Bottle Sport (1L, BPA-Free)", emoji: "🚰",
        description: "1-liter BPA-free Tritan water bottle. Leak-proof flip lid, carrying loop, measurement markings. Ideal for gym and sports activities.",
        price: 600, originalPrice: 600, category: "Sports", stock: 70, condition: "New",
        images: ["https://images.unsplash.com/photo-1523362628745-0c100150b504?w=400&q=80"],
        tags: ["water bottle", "1l", "bpa free", "sport", "gym"],
        rating: 4.4, reviewCount: 145, sold: 412, createdAt: Date.now() - 86400000 * 12,
      },
      {
        id: "prod_sp08", vendorId: "vendor_003", vendorName: "RUET Fashion Hub",
        name: "Gym Gloves (Weight Training)", emoji: "🥊",
        description: "Padded weight training gloves with wrist support wrap. Breathable mesh back, anti-slip palm. Sizes S/M/L/XL. Reduces calluses.",
        price: 800, originalPrice: 800, category: "Sports", stock: 35, condition: "New",
        images: ["https://images.unsplash.com/photo-1517344800994-80b20463999c?w=400&q=80"],
        tags: ["gym gloves", "weight training", "wrist support", "fitness"],
        rating: 4.5, reviewCount: 67, sold: 156, createdAt: Date.now() - 86400000 * 10,
      },
      {
        id: "prod_sp09", vendorId: "vendor_003", vendorName: "RUET Fashion Hub",
        name: "Chess Set (Wooden, Tournament Size)", emoji: "♟️",
        description: "Tournament-size wooden chess set. Weighted pieces with felt base, foldable board with storage. Ideal for inter-hall chess competitions.",
        price: 1400, originalPrice: 1800, category: "Sports", stock: 12, condition: "New",
        images: ["https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=400&q=80"],
        tags: ["chess", "wooden", "tournament", "board game", "strategy"],
        rating: 4.8, reviewCount: 34, sold: 67, createdAt: Date.now() - 86400000 * 8,
      },
      {
        id: "prod_sp10", vendorId: "vendor_003", vendorName: "RUET Fashion Hub",
        name: "Fitness Tracker Band (Steps+Sleep)", emoji: "⌚",
        description: "Smart fitness tracker: step count, calories, sleep monitoring, heart rate sensor, sedentary reminder. IP67 waterproof. 7-day battery.",
        price: 2400, originalPrice: 3000, category: "Sports", stock: 22, condition: "New",
        images: ["https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=400&q=80"],
        tags: ["fitness tracker", "smartband", "steps", "sleep", "heart rate"],
        rating: 4.4, reviewCount: 56, sold: 112, createdAt: Date.now() - 86400000 * 6,
      },

      // ── PERSONAL CARE & HYGIENE (5 products) ──
      {
        id: "prod_h01", vendorId: "vendor_004", vendorName: "Campus Canteen Supplies",
        name: "Hand Sanitizer 500ml (70% Alcohol)", emoji: "🧴",
        description: "70% isopropyl alcohol hand sanitizer gel. Kills 99.9% of germs, no water needed. Moisturizing formula with aloe vera. Non-sticky finish.",
        price: 350, originalPrice: 350, category: "Other", stock: 100, condition: "New",
        images: ["https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&q=80"],
        tags: ["sanitizer", "hygiene", "alcohol", "germ kill", "health"],
        rating: 4.6, reviewCount: 234, sold: 712, createdAt: Date.now() - 86400000 * 20,
      },
      {
        id: "prod_h02", vendorId: "vendor_004", vendorName: "Campus Canteen Supplies",
        name: "Face Mask (3-ply, Pack of 50)", emoji: "😷",
        description: "3-ply non-woven disposable face masks. BFE ≥95%, breathable, adjustable nose wire, ear loop. For classroom and lab use.",
        price: 480, originalPrice: 480, category: "Other", stock: 80, condition: "New",
        images: ["https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?w=400&q=80"],
        tags: ["mask", "face mask", "3ply", "disposable", "hygiene"],
        rating: 4.4, reviewCount: 178, sold: 534, createdAt: Date.now() - 86400000 * 18,
      },
      {
        id: "prod_h03", vendorId: "vendor_004", vendorName: "Campus Canteen Supplies",
        name: "Mosquito Repellent Cream 100g", emoji: "🦟",
        description: "DEET-free natural mosquito repellent cream. Contains eucalyptus and citronella. Effective up to 8 hours. Gentle on skin. No greasy residue.",
        price: 180, originalPrice: 220, category: "Other", stock: 120, condition: "New",
        images: ["https://images.unsplash.com/photo-1558981852-426c349454cd?w=400&q=80"],
        tags: ["mosquito repellent", "cream", "deet free", "natural", "skin"],
        rating: 4.5, reviewCount: 156, sold: 467, createdAt: Date.now() - 86400000 * 16,
      },
      {
        id: "prod_h04", vendorId: "vendor_004", vendorName: "Campus Canteen Supplies",
        name: "First Aid Kit (40-piece)", emoji: "🩹",
        description: "Compact first aid kit: bandages, antiseptic wipes, gauze, medical tape, scissors, tweezers, pain relief ointment. Zippered case.",
        price: 850, originalPrice: 850, category: "Other", stock: 35, condition: "New",
        images: ["https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=400&q=80"],
        tags: ["first aid", "kit", "bandage", "medical", "emergency"],
        rating: 4.7, reviewCount: 89, sold: 223, createdAt: Date.now() - 86400000 * 14,
      },
      {
        id: "prod_h05", vendorId: "vendor_004", vendorName: "Campus Canteen Supplies",
        name: "Electric Kettle 1.5L (Stainless)", emoji: "🫖",
        description: "1500W stainless steel electric kettle. Boils 1.5L in 4 minutes, auto shut-off, dry-boil protection, 360° base. Hall room essential.",
        price: 1200, originalPrice: 1500, category: "Other", stock: 40, condition: "Used",
        images: ["https://images.unsplash.com/photo-1544780374-2367caadc82a?w=400&q=80"],
        tags: ["kettle", "electric", "1.5l", "stainless", "hostel"],
        rating: 4.7, reviewCount: 145, sold: 389, createdAt: Date.now() - 86400000 * 12,
      },
    ];

    DB.setCollection("ruet_products", products);
  }

  // ── Orders ───────────────────────────────────────────────
  function _seedOrders() {
    const orders = [
      {
        id: "order_001", userId: "user_001", userName: "Rahim Hossain",
        items: [
          { productId: "prod_s01", name: "Casio FX-991EX Calculator", price: 1050, qty: 1, image: "" },
          { productId: "prod_s03", name: "A4 80GSM Notebook", price: 195, qty: 3, image: "" },
        ],
        subtotal: 1635, shipping: 0, discount: 0, total: 1635, status: "delivered",
        shippingAddress: "Hall-1 Room 212, RUET, Rajshahi", phone: "01711-333001",
        paymentMethod: "cash", createdAt: Date.now() - 86400000 * 15,
      },
      {
        id: "order_002", userId: "user_001", userName: "Rahim Hossain",
        items: [
          { productId: "prod_e09", name: "Arduino Uno R3 Starter Kit", price: 1800, qty: 1, image: "" },
          { productId: "prod_l05", name: "Breadboard + Jumper Kit", price: 380, qty: 1, image: "" },
        ],
        subtotal: 2180, shipping: 0, discount: 0, total: 2180, status: "processing",
        shippingAddress: "Hall-1 Room 212, RUET, Rajshahi", phone: "01711-333001",
        paymentMethod: "cash", createdAt: Date.now() - 86400000 * 2,
      },
      {
        id: "order_003", userId: "user_002", userName: "Sumaiya Begum",
        items: [
          { productId: "prod_e02", name: "Samsung Galaxy Buds2 Pro", price: 9500, qty: 1, image: "" },
          { productId: "prod_c04", name: "Lab Coat (White)", price: 680, qty: 1, image: "" },
          { productId: "prod_s06", name: "Highlighter Set (6 colors)", price: 220, qty: 2, image: "" },
        ],
        subtotal: 10620, shipping: 0, discount: 0, total: 10620, status: "shipped",
        shippingAddress: "Girls Hall Room 105, RUET, Rajshahi", phone: "01911-333002",
        paymentMethod: "cash", createdAt: Date.now() - 86400000 * 5,
      },
      {
        id: "order_004", userId: "user_003", userName: "Kamal Uddin",
        items: [
          { productId: "prod_b01", name: "Engineering Mathematics – Kreyszig", price: 1800, qty: 1, image: "" },
          { productId: "prod_b06", name: "Circuit Analysis – Hayt", price: 1700, qty: 1, image: "" },
          { productId: "prod_f01", name: "Nescafé Classic 200g", price: 480, qty: 2, image: "" },
        ],
        subtotal: 4460, shipping: 0, discount: 0, total: 4460, status: "confirmed",
        shippingAddress: "Hall-3 Room 318, RUET, Rajshahi", phone: "01611-333003",
        paymentMethod: "cash", createdAt: Date.now() - 86400000 * 7,
      },
      {
        id: "order_005", userId: "user_001", userName: "Rahim Hossain",
        items: [
          { productId: "prod_c01", name: "RUET Premium Polo T-Shirt", price: 580, qty: 2, image: "" },
          { productId: "prod_c02", name: "RUET Hoodie (Winter Fleece)", price: 1200, qty: 1, image: "" },
        ],
        subtotal: 2360, shipping: 0, discount: 0, total: 2360, status: "delivered",
        shippingAddress: "Hall-1 Room 212, RUET, Rajshahi", phone: "01711-333001",
        paymentMethod: "cash", createdAt: Date.now() - 86400000 * 20,
      },
      {
        id: "order_006", userId: "user_002", userName: "Sumaiya Begum",
        items: [
          { productId: "prod_e10", name: "Raspberry Pi 4 Model B (4GB)", price: 6500, qty: 1, image: "" },
          { productId: "prod_e15", name: "ESP32 Development Board", price: 450, qty: 3, image: "" },
        ],
        subtotal: 7850, shipping: 0, discount: 0, total: 7850, status: "delivered",
        shippingAddress: "Girls Hall Room 105, RUET, Rajshahi", phone: "01911-333002",
        paymentMethod: "cash", createdAt: Date.now() - 86400000 * 25,
      },
      {
        id: "order_007", userId: "user_004", userName: "Karim Uddin",
        items: [
          { productId: "prod_e01", name: "Sony WH-1000XM5", price: 35000, qty: 1, image: "" },
        ],
        subtotal: 35000, shipping: 0, discount: 0, total: 35000, status: "pending",
        shippingAddress: "Hall-2 Room 245, RUET, Rajshahi", phone: "01711-489403",
        paymentMethod: "cash", createdAt: Date.now() - 86400000 * 1,
      },
      {
        id: "order_008", userId: "user_005", userName: "Rahim Hossain",
        items: [
          { productId: "prod_f02", name: "Maggi 2-Minute Noodles (8 Pack)", price: 160, qty: 2, image: "" },
          { productId: "prod_c02", name: "RUET Hoodie (Winter Fleece)", price: 1200, qty: 1, image: "" },
        ],
        subtotal: 1520, shipping: 0, discount: 0, total: 1520, status: "shipped",
        shippingAddress: "Hall-1 Room 315, RUET, Rajshahi", phone: "01711-3789001",
        paymentMethod: "bkash", createdAt: Date.now() - 86400000 * 3,
      },
      {
        id: "order_009", userId: "user_006", userName: "Alamin Hossain",
        items: [
          { productId: "prod_b01", name: "Engineering Mathematics – Kreyszig", price: 1800, qty: 1, image: "" },
          { productId: "prod_s01", name: "Casio FX-991EX Calculator", price: 1050, qty: 1, image: "" },
        ],
        subtotal: 2850, shipping: 0, discount: 0, total: 2850, status: "delivered",
        shippingAddress: "Hall-2 Room 115, RUET, Rajshahi", phone: "01711-3789591",
        paymentMethod: "cash", createdAt: Date.now() - 86400000 * 4,
      },
      {
        id: "order_010", userId: "user_001", userName: "Sakib Al Hasan",
        items: [
          { productId: "prod_e09", name: "Arduino Uno R3 Starter Kit", price: 1800, qty: 2, image: "" },
        ],
        subtotal: 3600, shipping: 0, discount: 0, total: 3600, status: "processing",
        shippingAddress: "Hall-1 Room 212, RUET, Rajshahi", phone: "01711-333001",
        paymentMethod: "cash", createdAt: Date.now() - 86400000 * 8,
      },
      {
        id: "order_011", userId: "user_002", userName: "Sumaiya Begum",
        items: [
          { productId: "prod_f01", name: "Nescafé Classic 200g", price: 480, qty: 3, image: "" },
        ],
        subtotal: 1440, shipping: 0, discount: 0, total: 1440, status: "confirmed",
        shippingAddress: "Girls Hall Room 105, RUET, Rajshahi", phone: "01911-333002",
        paymentMethod: "cash", createdAt: Date.now() - 86400000 * 9,
      },
      {
        id: "order_012", userId: "user_003", userName: "Kamal Uddin",
        items: [
          { productId: "prod_c01", name: "RUET Premium Polo T-Shirt", price: 580, qty: 4, image: "" },
        ],
        subtotal: 2320, shipping: 0, discount: 0, total: 2320, status: "delivered",
        shippingAddress: "Hall-3 Room 318, RUET, Rajshahi", phone: "01611-333003",
        paymentMethod: "cash", createdAt: Date.now() - 86400000 * 12,
      },
      {
        id: "order_013", userId: "user_004", userName: "Karim Uddin",
        items: [
          { productId: "prod_l05", name: "Breadboard + Jumper Kit", price: 380, qty: 5, image: "" },
        ],
        subtotal: 1900, shipping: 0, discount: 0, total: 1900, status: "cancelled",
        shippingAddress: "Hall-2 Room 245, RUET, Rajshahi", phone: "01711-489403",
        paymentMethod: "bkash", createdAt: Date.now() - 86400000 * 11,
      },
      {
        id: "order_014", userId: "user_005", userName: "Rahim Hossain",
        items: [
          { productId: "prod_b06", name: "Circuit Analysis – Hayt", price: 1700, qty: 1, image: "" },
          { productId: "prod_s03", name: "A4 80GSM Notebook", price: 195, qty: 5, image: "" },
        ],
        subtotal: 2675, shipping: 0, discount: 0, total: 2675, status: "shipped",
        shippingAddress: "Hall-1 Room 315, RUET, Rajshahi", phone: "01711-3789001",
        paymentMethod: "cash", createdAt: Date.now() - 86400000 * 14,
      },
      {
        id: "order_015", userId: "user_006", userName: "Alamin Hossain",
        items: [
          { productId: "prod_e10", name: "Raspberry Pi 4 Model B (4GB)", price: 6500, qty: 1, image: "" },
          { productId: "prod_e02", name: "Samsung Galaxy Buds2 Pro", price: 9500, qty: 1, image: "" },
        ],
        subtotal: 16000, shipping: 0, discount: 0, total: 16000, status: "pending",
        shippingAddress: "Hall-2 Room 115, RUET, Rajshahi", phone: "01711-3789591",
        paymentMethod: "bkash", createdAt: Date.now() - 86400000 * 18,
      },
      {
        id: "order_016", userId: "user_001", userName: "Sakib Al Hasan",
        items: [
          { productId: "prod_c04", name: "Lab Coat (White)", price: 680, qty: 1, image: "" },
        ],
        subtotal: 680, shipping: 0, discount: 0, total: 680, status: "delivered",
        shippingAddress: "Hall-1 Room 212, RUET, Rajshahi", phone: "01711-333001",
        paymentMethod: "cash", createdAt: Date.now() - 86400000 * 16,
      },
    ];
    DB.setCollection("ruet_orders", orders);
  }

  // ── Reviews ──────────────────────────────────────────────
  function _seedReviews() {
    const reviews = [
      { id: "rev_001", productId: "prod_s01", userId: "user_001", userName: "Rahim Hossain", rating: 5, comment: "Best calculator for engineering students. QR code feature is amazing for checking answers!", createdAt: Date.now() - 86400000 * 14 },
      { id: "rev_002", productId: "prod_e09", userId: "user_002", userName: "Sumaiya Begum", rating: 5, comment: "Perfect starter kit for Arduino projects. Everything included, great value!", createdAt: Date.now() - 86400000 * 10 },
      { id: "rev_003", productId: "prod_c01", userId: "user_003", userName: "Kamal Uddin", rating: 4, comment: "Quality is excellent, fits well. The RUET logo embroidery looks professional.", createdAt: Date.now() - 86400000 * 8 },
      { id: "rev_004", productId: "prod_b01", userId: "user_001", userName: "Rahim Hossain", rating: 5, comment: "The best engineering math book. Clear explanations and good examples.", createdAt: Date.now() - 86400000 * 6 },
      { id: "rev_005", productId: "prod_f01", userId: "user_003", userName: "Kamal Uddin", rating: 4, comment: "Essential for late night studying. Good taste and keeps me awake during exams!", createdAt: Date.now() - 86400000 * 4 },
    ];
    DB.setCollection("ruet_reviews", reviews);
  }

  return { run, reset };
})();

Seeder.run();
